---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options: {}
lint: |
  env | sort
  yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
  echo "yaml lint done but do not exit in error for now"
platforms:
  - name: test-cluster
    groups:
      - k8s
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        namespace: ${CLUSTER_NAMESPACE:-osdk-test}
  lint:
    name: ansible-lint
    enabled: False
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
    K8S_AUTH_KUBECONFIG: ${KUBECONFIG:-'/root/.kube/config'}
scenario:
  name: test-cluster
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
